Site published on Tue Aug 20 20:19:50 MDT 2013

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
 git checkout master
+if [ $? -ne 0 ]; then
+  echo "Unable to checkout master! Do you have uncommited changes?"
+  rm -rf /tmp/jekyll
+  exit 1
+fi
 ./bin/index
 ./bin/sitemap
 git add -A .
